name: Deploy Portfolio to GitHub Pages

on:
  push:
    branches:
      - main  # Desplegar cuando haya cambios en la rama main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'  # Usa la versión de Node.js que prefieras

    - name: Install dependencies
      run: |
        npm ci

    - name: Build the app
      run: |
        npm run build -- --configuration=production

    - name: Deploy to GitHub Pages
      uses: angular/angular-cli-ghpages@v2
      with:
        build-dir: dist/portfolio  # La carpeta que contiene el build generado
        github-token: ${{ secrets.GITHUB_TOKEN }}